server:
  port: 8082

spring:
  application:
    name: stomp
  datasource:
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Seoul
    username: chatuser
    password: chatpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

jwt:
  secret: "change-this-secret-key-please-12345678901234567890"
  access-token-validity: 3600000   # 1시간 (ms)

logging:
  level:
    org.hibernate.SQL: debug               # 실제 실행되는 SQL
    org.hibernate.orm.jdbc.bind: trace     # 바인딩 파라미터 값 출력
